[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "your_project_name"
version = "0.1.0"
description = "A brief description of your project."
authors = [{ name = "Your Name", email = "your.email@example.com" }]
license = { file = "LICENSE" }
dependencies = [
    "absl-py",
    "aio-pika",
    "aiofiles",
    "aiogram",
    "aiohttp",
    "fire",
    "aiohttp-retry",
    "aiormq",
    "aiosignal",
    "APScheduler",
    "astunparse",
    "async-timeout",
    "attrs",
    "babel",
    "bidict",
    "blis",
    "boto3",
    "botocore",
    "CacheControl",
    "cachetools",
    "catalogue",
    "certifi",
    "cffi",
    "charset-normalizer",
    "click",
    "cloudpathlib",
    "cloudpickle",
    "colorama",
    "colorclass",
    "coloredlogs",
    "colorhash",
    "confection",
    "confluent-kafka",
    "cryptography",
    "cycler",
    "cymem",
    "dask",
    "dnspython",
    "docopt",
    "fbmessenger",
    "flatbuffers",
    "fonttools",
    "frozenlist",
    "fsspec",
    "future",
    "gast",
    "google-auth",
    "google-auth-oauthlib",
    "google-pasta",
    "greenlet",
    "grpcio",
    "h11",
    "h5py",
    "httptools",
    "humanfriendly",
    "idna",
    "jax",
    "jaxlib",
    "Jinja2",
    "jmespath",
    "joblib",
    "jsonpickle",
    "jsonschema",
    "keras",
    "kiwisolver",
    "langcodes",
    "language_data",
    "libclang",
    "locket",
    "marisa-trie",
    "Markdown",
    "markdown-it-py",
    "MarkupSafe",
    "matplotlib",
    "mattermostwrapper",
    "mdurl",
    "ml_dtypes",
    "msgpack",
    "multidict",
    "murmurhash",
    "networkx",
    "numpy",
    "oauthlib",
    "opt_einsum",
    "packaging",
    "pamqp",
    "partd",
    "pillow",
    "pluggy",
    "portalocker",
    "preshed",
    "prompt-toolkit",
    "propcache",
    "protobuf",
    "psycopg2-binary",
    "pyasn1",
    "pyasn1_modules",
    "pycparser",
    "pydantic",
    "pydot",
    "Pygments",
    "PyJWT",
    "pykwalify",
    "pymongo",
    "pyparsing",
    "pyreadline3",
    "pyrsistent",
    "python-crfsuite",
    "python-dateutil",
    "python-engineio",
    "python-socketio",
    "pytz",
    "PyYAML",
    "questionary",
    "randomname",
    "rasa",
    "rasa-sdk",
    "redis",
    "regex",
    "requests",
    "requests-oauthlib",
    "requests-toolbelt",
    "rich",
    "rocketchat-API",
    "rsa",
    "ruamel.yaml",
    "ruamel.yaml.clib",
    "s3transfer",
    "sanic",
    "Sanic-Cors",
    "sanic-jwt",
    "sanic-routing",
    "scikit-learn",
    "scipy",
    "sentry-sdk",
    "shellingham",
    "simple-websocket",
    "six",
    "sklearn-crfsuite",
    "slack_sdk",
    "smart-open",
    "spacy",
    "spacy-legacy",
    "spacy-loggers",
    "SQLAlchemy",
    "srsly",
    "structlog",
    "structlog-sentry",
    "tabulate",
    "tarsafe",
    "tensorboard",
    "tensorboard-data-server",
    "tensorflow",
    "tensorflow-estimator",
    "tensorflow-hub",
    "termcolor",
    "terminaltables",
    "thinc",
    "threadpoolctl",
    "toolz",
    "tqdm",
    "twilio",
    "typer",
    "typing-utils",
    "typing_extensions",
    "tzdata",
    "tzlocal",
    "ujson",
    "urllib3",
    "wasabi",
    "wcwidth",
    "websockets",
    "Werkzeug",
    "wrapt",
    "yarl",
    "zict",
]
